[phases.setup]
nixPkgs = [
  "python311",
  "poppler_utils",
  "tesseract5",
  "file",
  "pkg-config",
  "mesa",
  "libGL",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender"
]

[start]
cmd = "bash entrypoint.sh"
